-----------------------------------------------------------------------------------
-- Entraînement LMD : Langage de manipulation des données                        --
--                                                                               --
-- Requêtes DELETE :                                                             --
-- 1. Prendre connaissance de la ressource : https://sql.sh/cours/delete         --
-- 2. Compléter ce fichier avec vos propositions de requêtes                     --
-- 3. Pousser votre code sur votre Git                                           --
--                                                                               --
-- Merry query!                                                                  --
-----------------------------------------------------------------------------------

-- Le magasin qui avait été ouvert près de chez vous (si, si, souvenez vous... Et regardez le fichier "queries-insert.sql") ferme ses portes, ainsi va la vie.
--
-- Ecrire une requête qui supprime ce magasin.
--> 

-- L'utilisatrice Sharon Robinson décide de supprimer son compte.
-- En vertu du droit à l'effacement du Réglement Général pour la Protection des Données (RGPD) toutes ses informations personnelles 
-- devront être supprimées : https://www.cnil.fr/fr/comprendre-mes-droits/le-droit-leffacement-supprimer-vos-donnees-en-ligne
--
-- Ecrire une requête permettant de supprimer l'utilisatrice et toutes ses données associées.
--
-- Disclaimer : vous allez rencontrer un blocage lors de la suppression.
-- Renseignez vous sur la notion de "DELETE CASCADE" pour solutionner le problème : https://www.mysqltutorial.org/mysql-basics/mysql-on-delete-cascade/
-- Dans ce cas vous allez devoir passer par une modification des contraintes de clé étrangère.
-->
